import type { Metadata } from "next";
import "./globals.css"; // Make sure this imports the styles from the root CSS file

export const metadata: Metadata = {
  title: "CIFA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-aeonik antialiased">
        {children}
      </body>
    </html>
  );
}
